variable "run_id" {
  description = "Short unique identifier for this spin-up (e.g. 7k2q). Generated by the Python CLI."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9]{4,12}$", var.run_id))
    error_message = "run_id must be 4–12 lowercase alphanumerics."
  }
}

variable "size" {
  description = "VM sizing tier: small | medium | large."
  type        = string

  validation {
    condition     = contains(["small", "medium", "large"], var.size)
    error_message = "size must be one of: small, medium, large."
  }
}

variable "region" {
  description = "Azure region to deploy into."
  type        = string
  default     = "eastus2"
}

variable "allowed_cidr" {
  description = "CIDR allowed to reach RDP (TCP/3389). Typically the operator's public IP /32."
  type        = string

  validation {
    condition     = can(cidrnetmask(var.allowed_cidr))
    error_message = "allowed_cidr must be a valid CIDR (e.g. 203.0.113.5/32)."
  }
}

variable "admin_username" {
  description = "Local Windows admin username."
  type        = string
  default     = "awvmadmin"
}

variable "admin_password" {
  description = "Local Windows admin password. Generated by the Python CLI."
  type        = string
  sensitive   = true
}

variable "shutdown_timezone" {
  description = "IANA-style Windows timezone for the auto-shutdown schedule (e.g. 'Eastern Standard Time')."
  type        = string
  default     = "Eastern Standard Time"
}

variable "shutdown_time" {
  description = "Daily auto-shutdown time, 24h HHMM."
  type        = string
  default     = "0200"
}

variable "image_publisher" {
  description = "Marketplace image publisher."
  type        = string
  default     = "MicrosoftWindowsDesktop"
}

variable "image_offer" {
  description = "Marketplace image offer."
  type        = string
  default     = "windows-11"
}

variable "image_sku" {
  description = "Marketplace image SKU. Pinned but overridable; preflight validates it resolves in the region."
  type        = string
  default     = "win11-25h2-pro"
}

variable "image_version" {
  description = "Marketplace image version. 'latest' is acceptable for ephemeral test boxes."
  type        = string
  default     = "latest"
}

variable "tailscale_auth_key" {
  description = "Tailscale auth key for automatic tailnet join. Leave empty to skip Tailscale install."
  type        = string
  default     = ""
  sensitive   = true
}
